version: "1.0"
title: Open API for FSP Interoperability (FSPIOP)
description: Based on API Definition.docx updated on 2018-03-13 Version 1.0. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
license:
  name: Open API for FSP Interoperability (FSPIOP)
