version: "1.0" 
title: Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
description: Based on [API Definition version 1.0](https://github.com/mojaloop/mojaloop-specification/blob/develop/API%20Definition%20v1.0.pdf).


  **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
license:
  name: Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
  url: https://github.com/mojaloop/mojaloop-specification/blob/develop/LICENSE.md
